### ISSUE TITLE
Installing Steam creates "Install Steam" desktop file instead of "Steam"

### ISSUE THREAD

**Issue by XV-02** [pop-os/steam#13]
Recently, while I was looking at https://github.com/pop-os/nvidia-graphics-drivers/pull/201 (550) I noticed that the first time I installed Steam from either the Pop!_Shop or command line, the initial desktop file appeared to be for "Install Steam" with a generic application icon. 

Previously, the initial interaction as exposed through either the Application view or the Launcher was labeled "Steam" and had the Steam application icon. 

The end results are the same: If I launch either, Steam will do its self-install (behaviour which is consistent across Windows and Linux). So, the same processes are taking place. And once I've launched "Install Steam" and it has - ya know - installed, then the result is identical, with the correct Steam application name and icon exposed when subsequently attempting to launch, and everything launches correctly. 

This doesn't actually cause a regression in how the application functions, but I can see it presenting a speedbump for some users, and potentially being a source of confusion.

**Comment by leviport** [comment]
This happened when we synced with Debian packaging: https://github.com/pop-os/steam/pull/10#pullrequestreview-1738114172

We deemed it acceptable at the time, but yeah it's a little clunky.

**Comment by XV-02** [comment]
Looks like we've spotted this before, and been okay accepting it at this juncture, so, I'll close this for now.
